### ISSUE TITLE
☂️ Port DDA performance Optmization PRs

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#3073]
[Only some](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/419#issuecomment-1688237389) of @Aivean's [NPC performance optimizations](https://github.com/CleverRaven/Cataclysm-DDA/issues/45497) were ported to BN. This umbrella issue tracks them.

## Flag optimizations

```[tasklist]
### Flag & Big optimizations
- [ ] #3354
- [ ] port https://github.com/CleverRaven/Cataclysm-DDA/pull/45132
- [x] port https://github.com/CleverRaven/Cataclysm-DDA/pull/45277
- [x] port https://github.com/CleverRaven/Cataclysm-DDA/pull/45277
- [x] port https://github.com/CleverRaven/Cataclysm-DDA/pull/45516
- [ ] port https://github.com/CleverRaven/Cataclysm-DDA/pull/45346
- [x] port https://github.com/CleverRaven/Cataclysm-DDA/pull/54312
```

## NPC and other optimizations
```[tasklist]
- [ ] https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3074
- [ ] https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3075
- [ ] https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3076
- [ ] port https://github.com/CleverRaven/Cataclysm-DDA/pull/45461
- [ ] https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3078
- [ ] port https://github.com/CleverRaven/Cataclysm-DDA/pull/45426
- [ ] https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3079
- [ ] port https://github.com/CleverRaven/Cataclysm-DDA/pull/45026
```

## Considerations

- Ports should not cause significant merge conflict for following PRs:
	- #2216
	- #2250

#2250 may render some of those PRs obsolete, will have to check if it's the case.
also these PRs may have been already ported to BN, they also needs to be checked.

maybe just port https://github.com/CleverRaven/Cataclysm-DDA/pulls?q=is%3Apr+author%3AAivean+sort%3Acreated-asc+created%3A>2020-05-03 one by one?

**Comment by scarf005** [comment]
cc @Coolthulhu @olanti-p @joveeater
