### ISSUE TITLE
☂️ anime kemonomimi ear mutations

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#3202]
### Is your feature request related to a problem? Please describe.

- animal ear mutation gives ugliness, which is not realistic.
- it is scientifically proven (citation: me) that animal ears are cute.
- its tiles representation should be cuter
- having _accurate_ depiction of animal ears is critical to roleplay _cybernetically enhanced bionic catgirl warlord_.

### Describe the solution you'd like

- add anime ears to external tileset <https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/data/json/external_tileset/>
- give prettiness(negative ugliness) to existing animal ear mutations

### Additional context

- prior work done: https://github.com/Zupercharged/CDDA-Alternate-ear-graphics
- note to self: should move https://github.com/cataclysmbnteam/Cataclysm-BN/blob/6f24bb37142dccbd601548eb236d80c249ebbf8e/data/json/external_tileset/External%20Tileset%20Info.md to official docs alongside lang/notes as well.
```[tasklist]
### Tasks
- [x] ask permission to mainline CDDA-Alternate-ear-graphics
- [ ] https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3267
- [x] https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3268
```

**Comment by chaosvolt** [comment]
Amusing as this is, this does touch upon the greater issue that mutation ugliness does basically fuck-all and what little it does (if I recall it only really impacts whether a dynamic NPC will spawn hostile or not) could afford to be fleshed out such that mutant NPCs tolerate or even like ugly mutated PCs.

**Comment by scarf005** [comment]
that's a great idea. i think that could be made an individual issue, tho.
