### ISSUE TITLE
add style guide for documentation pages

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#3215]
> Please add all formatting things (heading 1's can't be used, we're going with - instead of * or +) in the guide for contributing docs.

_Originally posted by @RoyalFox2140 in https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3190#issuecomment-1731969054_
            
```[tasklist]
### Tasks
- [x] use `-` for unordered lists
- [x] prefer using aside syntax
- [x] add caveats on aside syntax
- [x] autoformat markdown with deno
- [x] avoid using h1(`#`)
- [x] front matters
```
