### ISSUE TITLE
port non-lethal JSON errors

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#3927]
port [CleverRaven/Cataclysm-DDA@`de2ff88` (#46337)](https://github.com/CleverRaven/Cataclysm-DDA/pull/46337/commits/de2ff881d67505a0eb4182abe9e5d33adfbb3d97)
```[tasklist]
### Tasks
- [x] port string_error for json array
- [x] remove mod blacklist
- [ ] migrate to typescript
```

**Comment by scarf005** [comment]
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/f92ffba9-7809-450d-b848-81046b918fd1)

how errors look like
