### ISSUE TITLE
:open_umbrella: add missing `looks_like`

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#3995]
## Summary

following entities are missing `looks_like`, and can be easily fixed by adding one.

## How to contribute

1. add `looks_like` field with suitable base sprite id.
2. open a PR, mentioning this PR (e.g: adds `looks_like` for `#3995`)
3. in the PR description, list which ids it covers.  
e.g: 
```
- f_debug_pump
- f_cardboard_floor
```
or: `"the whole terrain section"

## Checklist

```[tasklist]
### terrain
- [ ] t_deck_coating_no_roof_r
- [ ] t_deck_coating_no_roof_w
- [ ] t_railroad_track_ramp_down_high
- [ ] t_railroad_track_ramp_down_low
- [ ] t_railroad_track_ramp_up_high
- [ ] t_railroad_track_ramp_up_low
```

```[tasklist]
### furniture
- [ ] f_debug_pump
- [ ] f_cardboard_floor
- [ ] f_cardboard_roof
- [ ] f_cardboard_door_o
- [ ] f_cardboard_door
- [ ] f_file_cabinet
```

```[tasklist]
### item
- [ ] stock_small
- [ ] bio_reactoroverride
- [ ] bio_perpetual_test
- [ ] nonsensoleum
- [ ] debug_bio_fuel_cell
- [ ] fake_gridsolderingiron
- [ ] fake_gridwater_purifier
- [ ] fake_chemistry_set
- [ ] gridautoclave
- [ ] fake_autoclave
- [ ] fake_centrifuge
- [ ] schematics_haulerbot
- [ ] iron_ore
- [ ] rennet
- [ ] feral_jackboot_gun
- [ ] sourdough_young_uncovered
- [ ] sourdough_split_uncovered
- [ ] sourdough_starter_uncovered
- [ ] rubber_armor_small_quadruped
- [ ] superalloy_armor_small_quadruped
- [ ] masonrysaw_off
- [ ] five-point_harness
- [ ] power_armor_back_holster
- [ ] power_armor_holster
- [ ] power_armor_chest_rig
- [ ] power_armor_bscabbard
- [ ] power_armor_sheath
- [ ] crossbow_lever
- [ ] superalloy_armor_medium_quadruped
- [ ] salsify_omelette
- [ ] wild_veggy_omelette
- [ ] mushroom_omelette
- [ ] spanish_omelette
- [ ] xbow_string
- [ ] masonrysaw_on
- [ ] grinder_blade
- [ ] radio_car_base
- [ ] auger
- [ ] manual_barbaran
- [ ] manual_kickboxing
```

```[tasklist]
### vehicle_part
- [ ] engine_steam_turbine
- [ ] gyrocopter_rotors
- [ ] mounted_huge_crossbow
- [ ] mounted_rep_crossbow
- [ ] mounted_rm451_flamethrower
- [ ] mounted_laser_rifle_cheap
- [ ] mounted_gatling_mech_laser_rebuilt
- [ ] mounted_recon_mech_laser_rebuilt
- [ ] mounted_helsing
- [ ] mounted_tihar
- [ ] mounted_m202_flash
- [ ] mounted_surv_rocket_launcher
- [ ] mounted_paintballgun
- [ ] mounted_m1874_gatling
```

## How do i generate on locally for my tileset?

1. run `Reload Tileset`.

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/cf08e6a3-6075-40cf-bd05-c6bda9c8d783)

6. find lines after `INFO : Loaded tileset: <TILESET NAME>` in `debug.log`. for example:
```
12:00:40.716 INFO : Loaded tileset: UNDEAD_PEOPLE_BASE
12:00:40.717 INFO : Missing terrain: t_deck_coating_no_roof_r t_deck_coating_no_roof_w t_railroad_track_ramp_down_high t_railroad_track_ramp_down_low t_railroad_track_ramp_up_high t_railroad_track_ramp_up_low 
12:00:40.717 INFO : Missing furniture: f_debug_pump f_cardboard_floor f_cardboard_roof f_cardboard_door_o f_cardboard_door f_file_cabinet 
(...)
```
