### ISSUE TITLE
:open_umbrella: debug option to list all flags an item/monster/terrain has.

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#4301]
```[tasklist]
### Tasks
- [ ] debug option to display item flags
- [ ] debug option to display monster flags
- [ ] debug option to display terrain flags
```
